//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethink.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Context : DbContext
    {
        public Context()
            : base("name=Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Course_Trainee> Course_Trainee { get; set; }
        public virtual DbSet<CourseSections> CourseSections { get; set; }
        public virtual DbSet<DiscountPrice> DiscountPrice { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<HistorySolutions> HistorySolutions { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<PayCard> PayCard { get; set; }
        public virtual DbSet<PayLog> PayLog { get; set; }
        public virtual DbSet<PaySalary> PaySalary { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<RequestRegister> RequestRegister { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Solutions> Solutions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Testimonial> Testimonial { get; set; }
        public virtual DbSet<TraineeExam> TraineeExam { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
