//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethink.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorySolutions
    {
        public int Id { get; set; }
        public int IdQusetions { get; set; }
        public int IdTraineeExam { get; set; }
        public int IdSolutions { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Solutions Solutions { get; set; }
        public virtual TraineeExam TraineeExam { get; set; }
    }
}
