//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethink.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdCourseSections { get; set; }
    
        public virtual CourseSections CourseSections { get; set; }
    }
}
